ENVIRONMENT = "local"
os.putenv("DOCKER_DEFAULT_PLATFORM", "linux/amd64")

allow_k8s_contexts("docker-desktop")

docker_build("cartservice", "src/cartservice/src")
docker_build("checkoutservice", "src/checkoutservice")
docker_build("currencyservice", "src/currencyservice")
docker_build("emailservice", "src/emailservice")
docker_build("frontend", "src/frontend")
docker_build("paymentservice", "src/paymentservice")
docker_build("productcatalogservice", "src/productcatalogservice")
docker_build("recommendationservice", "src/recommendationservice")
docker_build("shippingservice", "src/shippingservice")

k8s_yaml(kustomize("kustomize/" + ENVIRONMENT))

k8s_resource("frontend", port_forwards="9000:8080")
