#!/usr/bin/env bash
set -euo pipefail
CLUSTER="kb-example"
SERVICE="doks-example"
REGION="lon1"
CONTEXT="do-${REGION}-${CLUSTER}"
doctl k8s cluster create ${CLUSTER} --region ${REGION}
kubectl --context ${CONTEXT} apply -f manifest.yaml
script/wait-for-service ${CONTEXT} ${SERVICE}
open http://$(kubectl --context ${CONTEXT} get service ${SERVICE} --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}")
