#!/usr/bin/env bash
set -euo pipefail
CLUSTER="example"
SERVICE="doks-example"
doctl k8s cluster create ${CLUSTER}
kubectl apply -f manifest.yaml
script/wait-for-service ${SERVICE}
open http://$(kubectl get service doks-example --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}")